services:

  muse:
    image: ghcr.io/museofficial/muse:latest
    container_name: muse
    hostname: muse
    restart: unless-stopped
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
      - ${DOCKER_VOLUME_STORAGE:-/mnt/docker-volumes}/muse:/data
    environment:
      - DISCORD_TOKEN=${DISCORD_TOKEN:?DISCORD_TOKEN must be set}
      - YOUTUBE_API_KEY=${YOUTUBE_API_KEY:?YOUTUBE_API_KEY must be set}
      - SPOTIFY_CLIENT_ID=${SPOTIFY_CLIENT_ID:?SPOTIFY_CLIENT_ID must be set}
      - SPOTIFY_CLIENT_SECRET=${SPOTIFY_CLIENT_SECRET:?SPOTIFY_CLIENT_SECRET must be set}